### ISSUE TITLE
Verify Email links don't open

### ISSUE THREAD

**Issue by triinity2221** [1fexd/LinkSheet#66] opened 2023-04-18 20:24 UTC
Hi Team, this app is super helpful. Just wanted to highlight one bug with the app, whenever I try to open links that are meant to verify emails, it leads to this redirect notice error, with out linksheet the URL opens perfectly if I keep Chrome as my default browser
![Screenshot_20230419_015322](https://user-images.githubusercontent.com/51398476/232896465-ba820be7-113b-4179-a87b-eb66b38c35b0.jpg)

**Comment by 1fexd** [comment] 2023-04-20 15:37
* Could you provide one such link (please make sure to redact url queries etc.)? 
* What settings in the link manipulation menu do you have enabled?

**Comment by triinity2221** [comment] 2023-04-21 07:39
Hi Team,
The issue was because I was using the clearURL option from link
manipulation settings. After disabling it, now it's working fine.

Thank you,
Rahul v poojari

**Comment by 1fexd** [comment] 2023-04-21 17:59
Yes - but could you still provide the link so I can check what's wrong with ClearURLs?

**Comment by TontyTon** [comment] 2023-05-26 19:42
@1fexd A similar problem with probably similar solution, that's why not opening a new issue.

Many companies use 3rd party services for emails, and all links in such emails (except for verification ones) have a lot of parameters, and if those parameters are removed, the link is not redirected to them required website because these 3rd party services add unique parameters to track usage, and some use the same parameter to decide to which page the link has to be redirected to. This is the case each and everytime for such emails for unsubscribing, as it has to be unique.

So, with ClearURL enabled, one can't open such links. So, whenever I have to open such link, I have to disable ClearURL, then open link and then enable again.

A probable solution is, in the popup to select apps, give option to use original link. So, if I click on that button, cleared url is changed to original url, and on clicking again original url is changed to cleared url (if someone clicks the button by mistake). Still cleared URL should be default if ClearURL is enabled in Settings.

If I wasn't clear or you need any other information, please ask.

**Comment by 1fexd** [comment] 2023-05-27 15:40
I will add such a button, but could you still provide such a link (**please make sure to redact all query parameters**)? Even with ClearURLs enabled, that shouldn't happen as ClearURLs is only supposed to remove tracking parameters.

**Comment by TontyTon** [comment] 2023-05-28 19:29
@1fexd 
I don't know if it will be helpful, as I have removed the domain too. Here cleared link wasn't working, but uncleared was.

Cleared link
http://*.*.*.com/gtrack?clientid=*&ul=*&pp=0

Uncleared link
http://*.*.*.com/gtrack?clientid=*&ul=*&ml=*&sl=*&pp=0

**Comment by 1fexd** [comment] 2023-05-28 20:20
> Same issue happens for spotify invite collaborator links, the links which give access to other people to become collaborator of playlists.

Thanks for the info, will look into wheter this is an issue with my implementation of ClearURLs or if it is an upstream issue.

**Comment by TontyTon** [comment] 2023-06-09 00:25
In latest nightly, Spotify collaborator links are working. But the email one is still not. But I think it's some specific case, so option to use the unprocessed link will be sufficient.

**Comment by 1fexd** [comment] 2023-06-11 20:58
* You mentioned the email link is for internal use, right? What does "internal" mean in this context? 
* Have you checked if the email link works on a desktop browser with the [ClearURLs](https://github.com/ClearURLs/Addon) extension?

**Comment by TontyTon** [comment] 2023-06-12 23:20
By 'internal' I mean, used at work.

I don't use ClearURL on desktop. Do I test with it? Will it be helpful?
I do use the ClearURL for uBO (https://github.com/DandelionSprout/adfilt/tree/master/ClearURLs%20for%20uBo), it's not complete implementation, due to restrictions by uBO. But it don't cause the issue.

Anyways, I think it's some very specific case, so I would suggest you to not spend too much time on figuring our what ClearURL rule is causing it.

**Comment by 1fexd** [comment] 2023-06-15 17:29
Just did a major rework of the ClearURLs implementation. Please grab the latest nightly release and check if it works now.

**Comment by TontyTon** [comment] 2023-06-17 23:50
Yup, that link is working now with ClearURLs enabled. Thanks.

My suggestion would still be to create that option if issue happens in future with some other link, I don't think it's possible to avoid false positives. 

_

Also, one issue I faced in nightly, didn't make separate issue since it's not in released.

Issue is Amp2Html's request timeout is not working sometimes. When internet wasn't available (but was connected to wifi), bottom sheet kept loading, loaded successfully sometimes instantly, but sometimes didn't load for more than 30 seconds, sometimes took more than 3-4 seconds (same link, so shouldn't be cache related), when I was trying to reproduce the issue. The timeout setting is set to '1'. Do you need some logs?
Do I make separate 'issue' for this?

**Comment by 1fexd** [comment] 2023-06-18 11:15
> My suggestion would still be to create that option if issue happens in future with some other link, I don't think it's possible to avoid false positives. You decide.

Yes it would make sense, the reason I am hesitant about adding such a button is the fact that the bottom sheet can already be veeeeery bloated because the user has the option to toggle so many buttons. 

> Issue is Amp2Html's request timeout is not working sometimes. When internet wasn't available (but was connected to wifi), bottom sheet kept loading, loaded successfully sometimes instantly, but sometimes didn't load for more than 30 seconds, sometimes took more than 3-4 seconds (same link, so shouldn't be cache related), when I was trying to reproduce the issue. The timeout setting is set to '1'. Do you need some logs?

I have noticed this issue myself already. No need to create an issue, will look into it.

**Comment by TontyTon** [comment] 2023-06-21 19:31
> Yes it would make sense, the reason I am hesitant about adding such a button is the fact that the bottom sheet can already be veeeeery bloated because the user has the option to toggle so many buttons.

Ah, makes sense. Maybe consider other options, like long tap on the link would change it to original one. It won't take up UI space.

> I have noticed this issue myself already. No need to create an issue, will look into it.

Ohk. Thanks.

**Comment by 1fexd** [comment] 2023-07-30 11:30
This may be introduced in #141 in 1.0.0. Closing this issue for now.

**Closed by 1fexd** 2023-07-30 11:30 UTC
Labels: awaiting feedback
