### ISSUE TITLE
Add support for ROOT

### ISSUE THREAD

**Issue by rajarshikhatua100** [1fexd/LinkSheet#340] opened 2024-03-11 04:41 UTC
### Feature description

add support for root along with shizuku, it will be easier for Magisk, KernelSU etc. users

**Comment by 1fexd** [comment] 2024-03-11 19:39
Duplicate of #282

**Closed by 1fexd** 2024-03-11 19:39 UTC
Labels: feature request

**Comment by rajarshikhatua100** [comment] 2024-03-11 20:22
oh, sorry. I searched for it and didn't see that one- skill issues from my side.
