### ISSUE TITLE
Cannot Open Play Store App via Youtube

### ISSUE THREAD

**Issue by Lorograch1** [1fexd/LinkSheet#52] opened 2023-04-01 20:03 UTC
Hi, thank you for this app. 

I followed the instructions and have set Linksheet as the default browser and when prompted on clicking on any link on an app, I chose Mull as the browser. However, when i clicked on a play store link on youtube, the menu doesnt show play store at all nor does it open the app, only the browser option and other non related apps show. Please advise.

**Comment by 1fexd** [comment] 2023-04-03 17:10
What Android version are you on? Could you provide a screen recording please?

**Comment by subhashay** [comment] 2023-04-04 07:42
Same issue here. Clicking on any links from YouTube opens it in webview and does not redirect to the respective app. Tried with GitHub, playstore links.

**Comment by subhashay** [comment] 2023-04-04 07:43
Ok closing and reopening the app worked!

**Comment by subhashay** [comment] 2023-04-04 07:47
Ok, another finding. Clicking on links from YouTube description only shows browser apps. Once I select any browser it then goes to the browser and then gets redirected to a specific app. Is this expected??

**Comment by subhashay** [comment] 2023-04-04 08:57
In conclusion, the issue is similar to what the reporter has mentioned.

**Comment by 1fexd** [comment] 2023-04-05 19:38
> Ok, another finding. Clicking on links from YouTube description only shows browser apps. Once I select any browser it then goes to the browser and then gets redirected to a specific app. Is this expected??

Please open a new issue.

**Comment by 1fexd** [comment] 2023-05-04 18:05
Probably, yes. Try turning on ClearURLs/Fastforward.

**Closed by 1fexd** 2023-05-04 18:05 UTC
Labels: awaiting feedback
